Dataset:
  name: boston_housing.csv
  target_column: medv
  train_size: 0.7
Preprocessing:
  numColumns:
  - black
  - age
  - tax
  numColsProcessor: mean
  numColsScale: true
  catColumns: []
  catColsProcessor: constant
model:
  modelName: None
  modelMode: train
modelParams:
  input_size: 12
  hidden_size: 64
  output_size: 1
  epochs: 200
  batch_size: 8
  lr: 0.0001
  dropout_rate: 0.3
  criterion: None
