Dataset:
  name: weatherHistory.csv
  target_column: Apparent Temperature (C)
  train_size: 0.7
Preprocessing:
  dropColumns:
  - Formatted Date
  numColumns:
  - Temperature (C)
  - Humidity
  - Wind Speed (km/h)
  - Wind Bearing (degrees)
  - Visibility (km)
  - Loud Cover
  - Pressure (millibars)
  numColsProcessor: mean
  numColsScale: true
  catColumns:
  - Summary
  - Precip Type
  - Daily Summary
  catColsProcessor: constant
model:
  modelName: weatherHistory.pth
  modelMode: evaluatee
modelParams:
  input_size: 249
  hidden_size: 64
  output_size: 1
  epochs: 5
  batch_size: 8
  lr: 0.0001
  dropout_rate: 0.3
  criterion: None
